name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:

  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-2019
        node:
          - 14
          - 16
          - 18
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test

  prebuild:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-2019
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g @electron/rebuild@^3.2.10
      - run: |
          for ver in 18.0.0 21.0.0 22.0.0; do electron-rebuild -v $ver; done;
        shell: bash
      - if: matrix.os == 'windows-2019'
        run: |
          for ver in 18.0.0 21.0.0 22.0.0; do electron-rebuild -v $ver --arch ia32; done;
        shell: bash
      - if: matrix.os == 'macos-latest'
        run: |
          for ver in 18.0.0 21.0.0 22.0.0; do electron-rebuild -v $ver --arch arm64; done;
        shell: bash
      - run: |
          for dir in bin/*/; do gzip -c $dir/better-sqlite3.node > ${dir%/*}.node.gz; done;
        shell: bash
      - name: release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "bin/*.node.gz"
          draft: true
